"""create API logs

Revision ID: 0ac865d6e3cc
Revises: 14a5f2e1d5e6
Create Date: 2025-07-04 14:15:43.168442

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ac865d6e3cc'
down_revision: Union[str, None] = '14a5f2e1d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
                    sa.Column('method', sa.String(length=10), nullable=True),
                    sa.Column('url', sa.Text(), nullable=True),
                    sa.Column('request_headers', sa.Text(), nullable=True),
                    sa.Column('request_body', sa.Text(), nullable=True),
                    sa.Column('response_status', sa.Integer(), nullable=True),
                    sa.Column('response_headers', sa.Text(), nullable=True),
                    sa.Column('response_body', sa.Text(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('terminals', 'site_id',
                    existing_type=sa.UUID(),
                    type_=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terminals', 'site_id',
                    existing_type=sa.String(),
                    type_=sa.UUID(),
                    existing_nullable=False)
    op.drop_table('api_logs')
    # ### end Alembic commands ###
