"""create API logs

Revision ID: 53853b8513a5
Revises: 0ac865d6e3cc
Create Date: 2025-07-04 15:08:53.055141

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53853b8513a5'
down_revision: Union[str, None] = '0ac865d6e3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'site_id',
                    existing_type=sa.UUID(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'site_id',
                    existing_type=sa.String(),
                    type_=sa.UUID(),
                    existing_nullable=True)
    # ### end Alembic commands ###
