"""Add user status and action times

Revision ID: 57fffa0d9e97
Revises: 53853b8513a5
Create Date: 2025-07-07 17:05:05.915423

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57fffa0d9e97'
down_revision: Union[str, None] = '53853b8513a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
                    sa.Column('term', sa.Integer(), nullable=False),
                    sa.Column('definition', sa.String(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_dictionaries_term'), 'dictionaries', ['term'], unique=False)
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_logout', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logout')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'status')
    op.drop_index(op.f('ix_dictionaries_term'), table_name='dictionaries')
    op.drop_table('dictionaries')
    # ### end Alembic commands ###
