"""save taxpayer ID

Revision ID: 97ca24114eb6
Revises: 3fd998241928
Create Date: 2025-07-10 08:23:07.766578

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97ca24114eb6'
down_revision: Union[str, None] = '3fd998241928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('taxpayer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'taxpayer_id')
    # ### end Alembic commands ###
