"""add transaction count

Revision ID: ac2ca0877420
Revises: 97ca24114eb6
Create Date: 2025-07-11 14:44:27.461999

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac2ca0877420'
down_revision: Union[str, None] = '97ca24114eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminals', sa.Column('transaction_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminals', 'transaction_count')
    # ### end Alembic commands ###
