"""create packages table

Revision ID: db401de28097
Revises: ac2ca0877420
Create Date: 2025-08-11 20:20:15.392923

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db401de28097'
down_revision: Union[str, None] = 'ac2ca0877420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('number_of_months', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('subscriptions', sa.Column('package_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'packages', ['package_id'], ['id'])
    op.drop_column('subscriptions', 'billing_cycle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_cycle', postgresql.ENUM('MONTHLY', 'ANNUAL', name='billingcycle'),
                                             autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'package_id')
    op.drop_table('packages')
    # ### end Alembic commands ###
